services:
  - type: web
    name: telegram-google-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python telegram_to_google.py
    envVars:
      - key: TELEGRAM_TOKEN
        sync: true
    secretFiles:
      - name: credentials.json
        mountPath: /etc/secrets/credentials.json

